ganesan-db:
    dbname: yugabyte
    host: 192.168.18.2
    #host: 172.17.0.1
    port: 5433
    user: yugabyte
    password: yugabyte
    jdbcurl: jdbc:postgresql://172.17.0.1:5432/ganesan-postgres
ganesan-dremio:
    host: 192.168.18.2
    #host: 172.17.0.1
    port: 9047
    odbcjdbcport: 31010
    user: ganesan
    password: password1
    jdbcurl: jdbc:dremio:direct=172.17.0.1:31010
